name: emarket_user
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get_it: any
  provider: ^6.0.3
  shared_preferences: any
  dio: ^4.0.0-prev2
  image_picker: any
  pin_code_fields: ^7.0.0
  google_maps_flutter_web: ^0.4.0
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: any
  geolocator: any
  shimmer_animation: ^2.0.0
  url_launcher: any
  webview_flutter: any
  firebase_core: any
  firebase_messaging: any
  flutter_local_notifications: any
  path_provider: any
  connectivity: ^3.0.3
  photo_view: any
  url_strategy: any
  carousel_slider: any
  fluro: any
  universal_html: any
  universal_ui: any
  image: ^3.0.2
  flutter_widget_from_html_core: ^0.8.5+1
  phone_number: ^1.0.0
  country_code_picker: ^2.0.2
  flutter_typeahead: ^4.0.0
  fwfh_selectable_text: ^0.8.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  modal_bottom_sheet: any

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700